metadata:
  id: x0bomZmzVz5j6lGl
  name: Test Workflow as Code
  description: '工作流: Test Workflow as Code'
  version: 1.0.0
  author: n8n-workflows-as-code
  tags: []
  created_at: '2025-11-03T14:30:03.072Z'
  updated_at: '2025-11-03T14:30:37.126Z'
  active: false
  archived: false
  trigger_count: 0
includes:
  nodes: ./nodes/**/*.yaml
  connections: ./connections/**/*.yaml
  settings: ./settings/**/*.yaml
  credentials: ./credentials/credential-mappings.yaml
  data:
    static: ./data/static/**/*.yaml
    pinned: ./data/pinned/**/*.yaml
build:
  output: ./workflow.json
  validate: true
  minify: false
